version: '3'

services:
  php:
    image: php:8.2-cli
    volumes:
      - ./:/var/www
    depends_on:
      - composer
  composer:
    image: composer
    volumes:
      - ./:/app
    command: composer dump-autoload